/*
 * Aquí esta contenida la vista del programa donde se obtienen los datos del
 * usuario, se procesan y se muestrala respuesta
 */
package SimulacionBillar;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author hp-PAVILION
 */
public class View extends javax.swing.JFrame {

    //Variables globales
    Controller _c = new Controller();
    DefaultTableModel tmesas, tdescuentos, thoras = new DefaultTableModel();
    String [] col;
    int [] col2;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        tmesas = (DefaultTableModel) tabMesas.getModel();
        tdescuentos = (DefaultTableModel) tabDescuentos.getModel();
        thoras = (DefaultTableModel) tabTiempoHoras.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtTitulo = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        txtRegistros = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabMesas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabDescuentos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTiempoHoras = new javax.swing.JTable();
        lblTotalIngresos = new javax.swing.JLabel();
        btnComenzarSimu = new javax.swing.JButton();
        btnGraficaIntervalo = new javax.swing.JButton();
        btnGraficaMesas = new javax.swing.JButton();
        btnGraficaDescuentos = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setText("Simulación del billar SOTUYO");

        lblDias.setText("Registros a simular:");

        lblResultado.setText("El resultado de simular con X días es:");

        tabMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabMesas);

        tabDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tabDescuentos);

        tabTiempoHoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabTiempoHoras);

        lblTotalIngresos.setText("Cantidad total de ingresos: ");

        btnComenzarSimu.setText("Comenzar la simulación");
        btnComenzarSimu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarSimuActionPerformed(evt);
            }
        });

        btnGraficaIntervalo.setText("Generar gráfica");
        btnGraficaIntervalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaIntervaloActionPerformed(evt);
            }
        });

        btnGraficaMesas.setText("Generar gráfica");
        btnGraficaMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaMesasActionPerformed(evt);
            }
        });

        btnGraficaDescuentos.setText("Generar gráfica");
        btnGraficaDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaDescuentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalIngresos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnGraficaIntervalo))
                    .addComponent(txtTitulo)
                    .addComponent(btnComenzarSimu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistros)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGraficaMesas)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficaDescuentos)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGraficaMesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGraficaIntervalo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtTitulo)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDias)
                                .addComponent(txtRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btnComenzarSimu)
                            .addGap(10, 10, 10)
                            .addComponent(lblResultado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblTotalIngresos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficaDescuentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Llena el encabezado de la tabla.
     * @param e Vector que tiene los títulos.
     * @param d DefaultTableModel al que se le aplica el vector.
     */
    public void llenarEncabezado(String[] e, DefaultTableModel d) {
        for (int i = 0; i < 2; i++) {
            d.addColumn(e[i]);
        }
    }

    /**
     * Botón generador.
     * @param evt 
     */
    private void btnComenzarSimuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarSimuActionPerformed
        //reiniciar tabla
        tmesas.setColumnCount(0);
        tmesas.setRowCount(0);
        tdescuentos.setColumnCount(0);
        tdescuentos.setRowCount(0);
        thoras.setColumnCount(0);
        thoras.setRowCount(0);
        
        //Llenado de la tabla
        String[] encabezado1 = {"Mesa", "veces usada"};
        llenarEncabezado(encabezado1, tmesas);
        String[] encabezado2 = {"Descuentos", "cantidad aplicada"};
        llenarEncabezado(encabezado2, tdescuentos);
        String[] encabezado3 = {"Intervalo de horas", "numero de veces"};
        llenarEncabezado(encabezado3, thoras);
        double aux=0;
        //Crear la llamada al numero random desde aqui para que sea igual en todos lados
        for (int i = 0; i < Integer.parseInt(txtRegistros.getText()); i++) {
            //Establecer randoms
            _c.setDescRandom(Math.random());
            _c.setMesaRandom(Math.random());
            _c.setTiempoHorasRandom(Math.random());
            //metodos
            _c.probabilidadMesa();
            _c.probabilidadDesc();
            _c.probabilidadTiempoHoras();
            aux = aux + _c.totalGanancia();
        }
        //Llenar tabla mesa
        int[] x = _c.getVecesMesa();
        String [] a = {"1",x[0]+""};
        tmesas.addRow(a);
        //recorrer
        System.out.println(x.length);
        for (int i = 3; i <= x.length+1; i++) {
            String [] b = {i+"",x[i-2]+""};
            System.out.println(""+Arrays.toString(b));
            tmesas.addRow(b);
        }
        
        //Llenar tabla descuento
        x = _c.getVecesdesc();
        String [] cero = {"0",x[0]+""};
        tdescuentos.addRow(cero);
        String [] cien = {"100",x[1]+""};
        tdescuentos.addRow(cien);
        String [] quince = {"15",x[2]+""};
        tdescuentos.addRow(quince);
        String [] cincuenta = {"50",x[3]+""};
        tdescuentos.addRow(cincuenta);
        //Llenar tabla horas
        x = _c.getVecesHora();
        String [] uno = {"0 a 0.3429",x[0]+""};
        thoras.addRow(uno);
        String [] dos = {"0.3429 a 6858",x[1]+""};
        thoras.addRow(dos);
        String [] tre = {"0.6858 a 1.0287",x[2]+""};
        thoras.addRow(tre);
        String [] cua = {"1.0287 a 1.3717",x[3]+""};
        thoras.addRow(cua);
        String [] cin = {"1.3717 a 1.7146",x[4]+""};
        thoras.addRow(cin);
        String [] sei = {"1.7146 a 2.0575",x[5]+""};
        thoras.addRow(sei);
        String [] sie = {"2.0575 a 2.4005",x[6]+""};
        thoras.addRow(sie);
        String [] och = {"2.4005 a 2.7434",x[7]+""};
        thoras.addRow(och);
        String [] nue = {"2.7434 a 3.0863",x[8]+""};
        thoras.addRow(nue);
        //Emitir resultado
        lblTotalIngresos.setText("$"+aux);
        System.out.println();
    }//GEN-LAST:event_btnComenzarSimuActionPerformed

    public void llenarArreglo(DefaultTableModel t){
        String [] aux1 = new String[t.getRowCount()];
        int [] aux2 = new int[t.getRowCount()];
        for (int i = 0; i < aux1.length; i++) {
            aux1[i] = String.valueOf(t.getValueAt(i, 0));
            aux2[i] = Integer.parseInt(String.valueOf(t.getValueAt(i, 1)));
        }
        col = aux1;
        col2 = aux2;
        System.out.println("\n\n"+Arrays.toString(col));
        System.out.println(""+Arrays.toString(col2));
    }
    
    private void btnGraficaDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaDescuentosActionPerformed
        llenarArreglo(tdescuentos);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < col.length; i++) {   
            dataset.setValue(col2[i],"descuento",col[i]);
        }
        JFreeChart chart = ChartFactory.createAreaChart("Probabilidad descuento", "porcentaje", "cantidad", dataset,
                PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);

        JFrame ventana = new JFrame("El grafico");
        ventana.getContentPane().add(panel);
        ventana.pack();
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnGraficaDescuentosActionPerformed

    private void btnGraficaMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaMesasActionPerformed
        llenarArreglo(tmesas);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < col.length; i++) {   
            dataset.setValue(col2[i],"mesas",col[i]);
        }
        JFreeChart chart = ChartFactory.createAreaChart("Probabilidad mesa", "mesa", "cantidad", dataset,
                PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);

        JFrame ventana = new JFrame("El grafico");
        ventana.getContentPane().add(panel);
        ventana.pack();
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnGraficaMesasActionPerformed

    private void btnGraficaIntervaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaIntervaloActionPerformed
        llenarArreglo(thoras);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < col.length; i++) {   
            dataset.setValue(col2[i],"horas",col[i]);
        }
        JFreeChart chart = ChartFactory.createAreaChart("Probabilidad horas", "intervalos", "cantidad", dataset,
                PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);

        JFrame ventana = new JFrame("El grafico");
        ventana.getContentPane().add(panel);
        ventana.pack();
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnGraficaIntervaloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarSimu;
    private javax.swing.JButton btnGraficaDescuentos;
    private javax.swing.JButton btnGraficaIntervalo;
    private javax.swing.JButton btnGraficaMesas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTotalIngresos;
    private javax.swing.JTable tabDescuentos;
    private javax.swing.JTable tabMesas;
    private javax.swing.JTable tabTiempoHoras;
    private javax.swing.JTextField txtRegistros;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
